# Generated by Django 3.1 on 2020-09-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grouptraining', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupcategory',
            unique_together={('name', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='grouptraining',
            unique_together={('name', 'slug')},
        ),
    ]
