# Generated by Django 3.1 on 2020-08-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouptraining', '0002_auto_20200827_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptraining',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grouptraining',
            name='subheader',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
