# Generated by Django 3.1 on 2020-09-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grouptraining', '0003_auto_20200910_1355'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='grouptraining',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='grouptraining',
            name='slug',
        ),
    ]
