# Generated by Django 3.1 on 2020-08-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouptraining', '0003_auto_20200827_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptraining',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
