# Generated by Django 3.1 on 2020-08-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouptraining', '0004_grouptraining_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptraining',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
