# Generated by Django 3.1 on 2020-08-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouptraining', '0007_auto_20200827_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptraining',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
