# Generated by Django 3.1 on 2020-08-31 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grouptraining', '0010_auto_20200830_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcategory',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='grouptraining',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
