# Generated by Django 3.1 on 2020-09-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grouptraining', '0011_auto_20200831_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptraining',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grouptraining.groupcategory'),
        ),
    ]
